apiVersion: apps/v1
kind: Deployment
metadata:
  name: iv-front-deployment
spec:
  replicas: 3 #초기 pod 수
  selector:
    matchLabels:
      app: frontend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1  # 다운 가능한 Pod 수
      maxSurge: 1        # 추가로 생성 가능한 Pod 수
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: interviewmate1/iv-frontend:v1
        ports:
        - containerPort: 3000
